// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PlayersTable, PlayersTableData } from "./tables/PlayersTable.sol";
import { TempConfigSet, TempConfigSetData } from "./tables/TempConfigSet.sol";
import { UniverseConfig, UniverseConfigData } from "./tables/UniverseConfig.sol";
import { SpaceTypeConfig, SpaceTypeConfigData } from "./tables/SpaceTypeConfig.sol";
import { UniverseZoneConfig, UniverseZoneConfigData } from "./tables/UniverseZoneConfig.sol";
import { PlanetLevelConfig } from "./tables/PlanetLevelConfig.sol";
import { PlanetTypeConfig } from "./tables/PlanetTypeConfig.sol";
import { SnarkConfig, SnarkConfigData } from "./tables/SnarkConfig.sol";
import { PlanetMetadata, PlanetMetadataData } from "./tables/PlanetMetadata.sol";
import { PlanetInitialValue, PlanetInitialValueData } from "./tables/PlanetInitialValue.sol";
import { Planet, PlanetData } from "./tables/Planet.sol";
import { PlanetOwner } from "./tables/PlanetOwner.sol";
import { Ticker, TickerData } from "./tables/Ticker.sol";
import { InnerCircle, InnerCircleData } from "./tables/InnerCircle.sol";
